ARG TERRAFORM_VERSION=latest
ARG OPENTOFU_VERSION=1

FROM hashicorp/terraform:$TERRAFORM_VERSION AS terraform

FROM ghcr.io/opentofu/opentofu:$OPENTOFU_VERSION-minimal AS opentofu

# tfupdate
FROM golang:1.26-alpine3.23 AS tfupdate
RUN apk --no-cache add make git

# A workaround for a permission issue of git.
# Since UIDs are different between host and container,
# the .git directory is untrusted by default.
# We need to allow it explicitly.
RUN git config --global --add safe.directory /work

# for testing
RUN apk add --no-cache bash
COPY --from=terraform /bin/terraform /usr/local/bin/
COPY --from=opentofu /usr/local/bin/tofu /usr/local/bin/

WORKDIR /work

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN make install
